spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 30MB
  datasource:
    url: jdbc:mysql://localhost:3306/attendance?serverTimezone=UTC&charsetEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true
    database: mysql
  web:
    resources:
      static-locations: classpath:/image/default/
server:
  port: 8080
file:
  upload:
    path:
      windows: D:\\attendance\\images\\
      linux: /opt/attendance/images/
