spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board?serverTimezone=UTC&charsetEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1q2w3e4r!@

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true
    database: mysql

server:
  port: 8080